language: node_js
node_js:
  - '0.12'
sudo: false
env:
  matrix:
    - GROUP=
  global:
    - secure: HhqwGErfcLXeOezA3L38eQTu8KdZ+FecmXMGvf/FEaQZ82XvELOSZ9O8O3HmxTRdM5fCjJja8CKWX2W871S4lIpiRhA/1OpQiz2V7lNseI2FML0fulukYCFkoo/uYPNjsj9AC8cF9CSGTJ8+RNgxPrFYoA9uisaH+91miGbJuVLZOa+CuSrL6fmPX7Env3YxV6fnufWy/bPH7oc3VyIzRQyjIVEwFaCd5omaWPqmO4eVhsefYEB/B3LX05ZgnoXWevZ4OnBq4Up3o+RjhkJKtnF7Huur0UgH2BaOQNm2b/MKBax9CbE9iHp+63tPT8q7WVP7giB+KUZyru96bUzdnkIFWMcm5bPlPsBmpfgkGzI4Js/xTLXIBNCtByspTEyhVEaX8ljd9XZ0Afm8iTvuLwGALE3xuHWvW29vHgk/fTeXOftoBcfaQRoVFNJuA/NMrox1Ya3yu+dq3epmWgwJ+IGdyXQzSp2cXDxLlg5ePbliBvhZHL7a7C5PZGab7fv4aTNa4HgTOjtWO7tiCj7u/2XPMQnuBUAtZUSpc9PpEMxgWNPuXuBimntYMfxG7iGNfkgq2FGW5Fz4HvIvSsnZyY4LF35SuZIbSTICHtuIYwV36EeHmM3cQmMAspRRfGV0dbsT1JQd7zUmVxYRBzukuntuVswQlN8H+r/oypcZwB0=
before_install:
  - chmod +x ./scripts/travis_install.sh
  - chmod +x ./scripts/travis_script.sh
  - chmod +x ./scripts/travis_after_success.sh
install:
  - ./scripts/travis_install.sh
script:
  - ./scripts/travis_script.sh
after_success:
  - ./scripts/travis_after_success.sh
deploy:
  provider: npm
  email: sccolbert@gmail.com
  api_key: heW/ijXVjlu15PDOFO5dEE+qHiahe+eh09YTuI0nSDBGx++OvWRr1N1APRhxJ/gozJjS7SgRuc/oc7W3iJDgfMimr5ua09evteTu266A/Mqv9Ib5WnDT6wMEadGV6GqlnHAkATSTlrJieBq+NQOJzyUSJy6Ny47nceVz83sxU0z7eGIZXMM0AqyB82RFVuI3lj5G4bvP/8bg1Pwz+txCA+BZytTKumqJgibTRyDR0Mpq/EehXVtCu06UF0CDFw4HdB/LBl3f7oDRvBKdwtLdmx6DtJTd7HbDPndxdz4YlxdzrnX6NagvaUFkuCT80EcVoYy5zdRe944ng8wnvSg7Mx4PDRMPyk79mzkBVCy4k5xvVndf/hwwdq5vzCxBJyS7VTYWWaPwjgwfkNysV4esWXCNlNLESwjSvDPGJXWUObo4c8H11T1MBKOfFhKTHNsi5eLZCHk9k78NtAHcL/1ivilpp4GQtIhfXRmOpng0SJhXcdhCTG1PsbQE990cQ68EqXHDrftE7Ml5k34sD7+FRmBrIaLOB4OKgMZdSNrxNTtBgQPcF9ZPLPuMIWuIsBUMQ9tXk6gUvdQUx9Ye6RmnwStH8L2HA39FmW1zA4vg5fgrcdqyTcwHiPGuEYxvOr37MzngmcRbARlZxDDX07Mz4birZoAdeBXHZtPH0eE9n+8=
  on:
    tags: true
