language: node_js
node_js:
  - '0.12'
sudo: false
env:
  matrix:
    - GROUP=
  global:
    - secure: HhqwGErfcLXeOezA3L38eQTu8KdZ+FecmXMGvf/FEaQZ82XvELOSZ9O8O3HmxTRdM5fCjJja8CKWX2W871S4lIpiRhA/1OpQiz2V7lNseI2FML0fulukYCFkoo/uYPNjsj9AC8cF9CSGTJ8+RNgxPrFYoA9uisaH+91miGbJuVLZOa+CuSrL6fmPX7Env3YxV6fnufWy/bPH7oc3VyIzRQyjIVEwFaCd5omaWPqmO4eVhsefYEB/B3LX05ZgnoXWevZ4OnBq4Up3o+RjhkJKtnF7Huur0UgH2BaOQNm2b/MKBax9CbE9iHp+63tPT8q7WVP7giB+KUZyru96bUzdnkIFWMcm5bPlPsBmpfgkGzI4Js/xTLXIBNCtByspTEyhVEaX8ljd9XZ0Afm8iTvuLwGALE3xuHWvW29vHgk/fTeXOftoBcfaQRoVFNJuA/NMrox1Ya3yu+dq3epmWgwJ+IGdyXQzSp2cXDxLlg5ePbliBvhZHL7a7C5PZGab7fv4aTNa4HgTOjtWO7tiCj7u/2XPMQnuBUAtZUSpc9PpEMxgWNPuXuBimntYMfxG7iGNfkgq2FGW5Fz4HvIvSsnZyY4LF35SuZIbSTICHtuIYwV36EeHmM3cQmMAspRRfGV0dbsT1JQd7zUmVxYRBzukuntuVswQlN8H+r/oypcZwB0=
before_install:
  - chmod +x ./scripts/travis_install.sh
  - chmod +x ./scripts/travis_script.sh
  - chmod +x ./scripts/travis_after_success.sh
install:
  - ./scripts/travis_install.sh
script:
  - ./scripts/travis_script.sh
after_success:
  - ./scripts/travis_after_success.sh
deploy:
  provider: npm
  email: sccolbert@gmail.com
  api_key: nEuf37G76iufCAJlJlQTTqAkpsWzpAHYXhoPvXtDyfCeLTlTJiSIxrFX7x53z5mKwLeD9YlBfwa3BXJgvSBCvV9BbV1PE3I5Mw7cfVu8ymTsKZV90Eaeecye7m/pXC7hQ3lejkWE892qHeafArZSkyXyBVNEZD9QR/hYWa6KLQ29D9RjmCb6BainEyzGa0vUseD8z5COaj/mqSe77soSHwifPPdHlCQEYojN1zh8XXGrf+h7uJQW6t4PDQ93gDkr9xQlge10k4PxOxOYJ4sgfb3ZMVJCSJSfglnBSjAz0enyX4I2A4BRmNdyDKr22KAZlPdxLAda61Oz8DeyK6IkMswsMA0BoRavrtUWyBd0mtc/F2zZeyVRIDpMCNQhLnoicJvfCAYFcG2t9FMQsDoe0BS0byctykJjkcCsJNpirvLISpog+IExYOimeHUa8TtCVGfHY5Z07jT9UpkWH0q6C6dJ9W8/i7y6FoEwF+CPuIXOzDNRXl3odKvmDISGa5pvsdHHqWQzWdOnIicvXt86A2HORLQ+xxIvnLU96AyU6Z3otfc/G0z1Zf40d/LBAx8bPvFZz2zo+4V4le0rKkTyydDufbXoBuwqg4q487YKQEKrtOnuxd+U3Z1SIqNq7hx4lJ0xkhSmRX00mDSdiohFOWCSP+RBd3lGl6HBIb0/MR4=
  on:
    tags: true
